modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"

[[mods]]
modId="template_mod"
version="1.0.0"
displayName="Template Mod"
displayURL=""
authors="Licit Lettuce"
credits="Mod by Licit Lettuce"
description='''Description Goes Here'''
logoFile="logo.png"

[[dependencies.otherspace]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"