modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"

[[mods]]
modId="mario_64_paintings"
version="1.0.3"
displayName="Mario 64 Paintings"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mario-64-paintings"
authors="licitLettuce"
credits="licitLettuce (Lead Developer, Artist, Game Design) -All assets included in this mod are based off of assets created by Nintendo"
description='''Adds Iconic Paintings from Super Mario 64'''
logoFile="logo.png"

[[dependencies.otherspace]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"